function [meshgridK,meshgridDelta] = createMeshGridSLIPPER(result)
%CREATEMESHGRID Create mesh grid for finding SLIPPER fixed points
%   A 2D mesh grid for a given range of dimensionless k and delta defined in
%   the optParms will be generated by running this function.
%
x = linspace(optParms.kMin, optParms.kMax, optParms.sampledNumberK);
y = linspace(optParms.deltaMin, optParms.deltaMax, optParms.sampledNumberDelta);
[meshgridK, meshgridDelta] = meshgrid(x, y);
end

