function c = boundaryConst(l,theta,ld,thetad,xEnd,zEnd,xdEnd,zdEnd,g,k,beta)
%BOUNDARYCONST
%    C = BOUNDARYCONST(L,THETA,LD,THETAD,XEND,ZEND,XDEND,ZDEND,G,K,BETA)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    02-Sep-2018 15:53:54

t2 = conj(theta);
t3 = conj(l);
t4 = cos(t2);
t5 = sin(t2);
t6 = conj(ld);
t7 = conj(thetad);
t8 = t5.*t6+t3.*t4.*t7;
c = [conj(xEnd)+t3.*t4,conj(zEnd)-t3.*t5,conj(xdEnd)+t4.*t6-t3.*t5.*t7,conj(zdEnd)-t5.*t6-t3.*t4.*t7,t3-1.0,t2-conj(beta),t3.^2.*t5.^2+t8.^2-1.0];
