function c = boundaryConstSingle(l0,theta0,l0d,theta0d,lEnd,thetaEnd,lEndd,thetaEndd,g,k,beta)
%BOUNDARYCONSTSINGLE
%    C = BOUNDARYCONSTSINGLE(L0,THETA0,L0D,THETA0D,LEND,THETAEND,LENDD,THETAENDD,G,K,BETA)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    07-Sep-2018 00:05:34

t2 = sin(thetaEnd);
t3 = cos(thetaEnd);
t4 = sin(theta0);
t5 = cos(theta0);
c = [l0d.^2+l0.^2.*theta0d.^2-1.0,l0d.*t5-lEndd.*t3-l0.*t4.*theta0d+lEnd.*t2.*thetaEndd,-conj(sqrt(g.*sin(beta).*2.0+lEndd.^2.*t2.^2-g.*lEnd.*t2.*2.0+lEnd.^2.*t3.^2.*thetaEndd.^2+lEnd.*lEndd.*t2.*t3.*thetaEndd.*2.0))+l0d.*t4+l0.*t5.*theta0d];
