function c = boundaryCost(l0,theta0,l0d,theta0d,lEnd,thetaEnd,lEndd,thetaEndd,g,k,beta)
%BOUNDARYCOST
%    C = BOUNDARYCOST(L0,THETA0,L0D,THETA0D,LEND,THETAEND,LENDD,THETAENDD,G,K,BETA)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    08-Sep-2018 15:20:40

t2 = lEnd-1.0;
t3 = l0d.^2+l0.^2.*theta0d.^2-1.0;
t5 = sin(thetaEnd);
t6 = cos(thetaEnd);
t7 = sin(theta0);
t8 = cos(theta0);
t4 = l0d.*t8-lEndd.*t6-l0.*t7.*theta0d+lEnd.*t5.*thetaEndd;
t9 = -conj(sqrt(g.*sin(beta).*2.0+lEndd.^2.*t5.^2-g.*lEnd.*t5.*2.0+lEnd.^2.*t6.^2.*thetaEndd.^2+lEnd.*lEndd.*t5.*t6.*thetaEndd.*2.0))+l0d.*t7+l0.*t8.*theta0d;
c = [t2.^2,t3.^2,t4.^2,t9.^2];
