function c = boundaryConstSingleFake(l0,theta0,l0d,theta0d,lEnd,thetaEnd,lEndd,thetaEndd,g,k,beta)
%BOUNDARYCONSTSINGLEFAKE
%    C = BOUNDARYCONSTSINGLEFAKE(L0,THETA0,L0D,THETA0D,LEND,THETAEND,LENDD,THETAENDD,G,K,BETA)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    07-Sep-2018 00:05:35

t2 = sin(theta0);
t3 = sin(thetaEnd);
t4 = cos(theta0);
t5 = cos(thetaEnd);
c = [l0d.^2+l0.^2.*theta0d.^2-1.0,l0d.*t4-lEndd.*t5.*5.0-l0.*t2.*theta0d+lEnd.*t3.*thetaEndd.*5.0,l0d.*t2+lEndd.*t3.*5.0+l0.*t4.*theta0d+lEnd.*t5.*thetaEndd.*5.0];
