function c = boundaryCost(l0,theta0,l0d,theta0d,lEnd,thetaEnd,lEndd,thetaEndd,g,k,beta)
%BOUNDARYCOST
%    C = BOUNDARYCOST(L0,THETA0,L0D,THETA0D,LEND,THETAEND,LENDD,THETAENDD,G,K,BETA)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    11-Sep-2018 14:31:21

t3 = sin(thetaEnd);
t4 = sin(theta0);
t5 = cos(thetaEnd);
t6 = cos(theta0);
t2 = l0d.*t6-lEndd.*t5-l0.*t4.*theta0d+lEnd.*t3.*thetaEndd;
t7 = -conj(sqrt(g.*t4.*2.0+lEndd.^2.*t3.^2-g.*lEnd.*t3.*2.0+lEnd.^2.*t5.^2.*thetaEndd.^2+lEnd.*lEndd.*t3.*t5.*thetaEndd.*2.0))+l0d.*t4+l0.*t6.*theta0d;
c = [t2.^2,t7.^2];
