function c = boundaryCost(l0,theta0,l0d,theta0d,lEnd,thetaEnd,lEndd,thetaEndd,g,k,beta)
%BOUNDARYCOST
%    C = BOUNDARYCOST(L0,THETA0,L0D,THETA0D,LEND,THETAEND,LENDD,THETAENDD,G,K,BETA)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    10-Sep-2018 16:12:27

t3 = sin(thetaEnd);
t4 = cos(thetaEnd);
t5 = sin(theta0);
t6 = cos(theta0);
t2 = l0d.*t6-lEndd.*t4-l0.*t5.*theta0d+lEnd.*t3.*thetaEndd;
t7 = -conj(sqrt(g.*sin(beta).*2.0+lEndd.^2.*t3.^2-g.*lEnd.*t3.*2.0+lEnd.^2.*t4.^2.*thetaEndd.^2+lEnd.*lEndd.*t3.*t4.*thetaEndd.*2.0))+l0d.*t5+l0.*t6.*theta0d;
c = [t2.^2,t7.^2];
