function costStance = costStance(l,theta,ld,thetad,h,g)
%COSTSTANCE
%    COSTSTANCE = COSTSTANCE(L,THETA,LD,THETAD,H,G)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    09-Sep-2018 20:54:59

costStance = g.*h.*l.*sin(theta);
