function costFlight = costFlight(xF,zF,xFd,zFd,h)
%COSTFLIGHT
%    COSTFLIGHT = COSTFLIGHT(XF,ZF,XFD,ZFD,H)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    03-Sep-2018 19:41:32

costFlight = h.*(xFd.^2+zFd.^2);
