function tFlightEnd = getFlightTime(lEnd,thetaEnd,lEndd,thetaEndd,theta0,g)
%GETFLIGHTTIME
%    TFLIGHTEND = GETFLIGHTTIME(LEND,THETAEND,LENDD,THETAENDD,THETA0,G)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    11-Sep-2018 14:31:21

t2 = sin(thetaEnd);
t3 = cos(thetaEnd);
tFlightEnd = (lEndd.*t2+sqrt(g.*sin(theta0).*2.0+lEndd.^2.*t2.^2-g.*lEnd.*t2.*2.0+lEnd.^2.*t3.^2.*thetaEndd.^2+lEnd.*lEndd.*t2.*t3.*thetaEndd.*2.0)+lEnd.*t3.*thetaEndd)./g;
