function tFlightEnd = getFlightTime(lEnd,thetaEnd,lEndd,thetaEndd,g,k,beta)
%GETFLIGHTTIME
%    TFLIGHTEND = GETFLIGHTTIME(LEND,THETAEND,LENDD,THETAENDD,G,K,BETA)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    08-Sep-2018 15:20:40

t2 = sin(thetaEnd);
t3 = cos(thetaEnd);
tFlightEnd = (lEndd.*t2+sqrt(g.*sin(beta).*2.0+lEndd.^2.*t2.^2-g.*lEnd.*t2.*2.0+lEnd.^2.*t3.^2.*thetaEndd.^2+lEnd.*lEndd.*t2.*t3.*thetaEndd.*2.0)+lEnd.*t3.*thetaEndd)./g;
