function jacobianStance = jacobianStanceDym(l,theta,ld,thetad,g,k)
%JACOBIANSTANCEDYM
%    JACOBIANSTANCE = JACOBIANSTANCEDYM(L,THETA,LD,THETAD,G,K)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    02-Sep-2018 11:26:56

t2 = cos(theta);
t3 = g.*t2;
t4 = 1.0./l;
jacobianStance = reshape([k-thetad.^2,-1.0./l.^2.*(t3+ld.*thetad.*2.0),t3,-g.*t4.*sin(theta),0.0,t4.*thetad.*2.0,l.*thetad.*-2.0,ld.*t4.*2.0,1.0,0.0,0.0,1.0],[2,6]);
