function jacobianCostStanceH = jacobianCostStanceH(l,theta,ld,thetad,h,g)
%JACOBIANCOSTSTANCEH
%    JACOBIANCOSTSTANCEH = JACOBIANCOSTSTANCEH(L,THETA,LD,THETAD,H,G)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    04-Sep-2018 13:56:14

jacobianCostStanceH = ld.^2+l.^2.*thetad.^2+g.*l.*sin(theta);
