function jacobianCostFlightX = jacobianCostFlightX(xF,zF,xFd,zFd,h,g)
%JACOBIANCOSTFLIGHTX
%    JACOBIANCOSTFLIGHTX = JACOBIANCOSTFLIGHTX(XF,ZF,XFD,ZFD,H,G)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    09-Sep-2018 20:55:00

jacobianCostFlightX = [0.0,g.*h,h.*xFd.*2.0,h.*zFd.*2.0,0.0,0.0];
