function jacobianStanceEndPattern = jacobianBoundaryConstXSEndSinglePattern
%JACOBIANBOUNDARYCONSTXSENDSINGLEPATTERN
%    JACOBIANSTANCEENDPATTERN = JACOBIANBOUNDARYCONSTXSENDSINGLEPATTERN

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    06-Sep-2018 18:03:20

jacobianStanceEndPattern = reshape([0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,6]);
