function jacobianCostFlightH = jacobianCostFlightH(xF,zF,xFd,zFd,h)
%JACOBIANCOSTFLIGHTH
%    JACOBIANCOSTFLIGHTH = JACOBIANCOSTFLIGHTH(XF,ZF,XFD,ZFD,H)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    03-Sep-2018 19:41:32

jacobianCostFlightH = xFd.^2+zFd.^2;
