function jacobianStance0Pattern = jacobianBoundaryConstXS0SinglePattern
%JACOBIANBOUNDARYCONSTXS0SINGLEPATTERN
%    JACOBIANSTANCE0PATTERN = JACOBIANBOUNDARYCONSTXS0SINGLEPATTERN

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    06-Sep-2018 18:03:19

jacobianStance0Pattern = reshape([1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,6]);
