function jacobianStanceEndPattern = jacobianBoundaryConstXSEndSinglePatternFake
%JACOBIANBOUNDARYCONSTXSENDSINGLEPATTERNFAKE
%    JACOBIANSTANCEENDPATTERN = JACOBIANBOUNDARYCONSTXSENDSINGLEPATTERNFAKE

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    08-Sep-2018 11:26:37

jacobianStanceEndPattern = reshape([1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[4,6]);
