function jacobianStanceEnd = jacobianBoundaryConstXSEndSingle(lEnd,thetaEnd,lEndd,thetaEndd,g,k,beta)
%JACOBIANBOUNDARYCONSTXSENDSINGLE
%    JACOBIANSTANCEEND = JACOBIANBOUNDARYCONSTXSENDSINGLE(LEND,THETAEND,LENDD,THETAENDD,G,K,BETA)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    06-Sep-2018 18:03:19

t2 = sin(thetaEnd);
t3 = cos(thetaEnd);
t4 = thetaEndd.^2;
t5 = t3.^2;
t6 = lEndd.^2;
t7 = t2.^2;
t8 = t6.*t7;
t9 = sin(beta);
t10 = g.*t9.*2.0;
t11 = lEnd.^2;
t12 = t4.*t5.*t11;
t13 = lEnd.*lEndd.*t2.*t3.*thetaEndd.*2.0;
t20 = g.*lEnd.*t2.*2.0;
t14 = t8+t10+t12+t13-t20;
t15 = sqrt(t14);
t16 = conj(t15);
t17 = 1.0./t16;
t18 = thetaEnd.*2.0;
t19 = sin(t18);
t21 = lEndd.*t2;
t22 = lEnd.*t3.*thetaEndd;
t23 = t21+t22;
jacobianStanceEnd = reshape([0.0,t2.*thetaEndd,-t17.*(-g.*t2+lEnd.*t4.*t5+lEndd.*t2.*t3.*thetaEndd),0.0,t23,t17.*(t6.*t19-g.*lEnd.*t3.*2.0-t4.*t11.*t19+lEnd.*lEndd.*thetaEndd.*cos(t18).*2.0).*(-1.0./2.0),0.0,-t3,-t2.*t17.*t23,0.0,lEnd.*t2,-lEnd.*t3.*t17.*t23,0.0,0.0,0.0,0.0,0.0,0.0],[3,6]);
