function jacobianStanceEnd = jacobianBoundaryConstXSEndSingleFake(lEnd,thetaEnd,lEndd,thetaEndd,g,k,beta)
%JACOBIANBOUNDARYCONSTXSENDSINGLEFAKE
%    JACOBIANSTANCEEND = JACOBIANBOUNDARYCONSTXSENDSINGLEFAKE(LEND,THETAEND,LENDD,THETAENDD,G,K,BETA)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    07-Sep-2018 00:05:35

t2 = sin(thetaEnd);
t3 = cos(thetaEnd);
jacobianStanceEnd = reshape([0.0,t2.*thetaEndd.*5.0,t3.*thetaEndd.*5.0,0.0,lEndd.*t2.*5.0+lEnd.*t3.*thetaEndd.*5.0,lEndd.*t3.*5.0-lEnd.*t2.*thetaEndd.*5.0,0.0,t3.*-5.0,t2.*5.0,0.0,lEnd.*t2.*5.0,lEnd.*t3.*5.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,6]);
