function jacobianFlight = jacobianBoundaryConstXEnd(xEnd,zEnd,xdEnd,zdEnd,g,k,beta)
%JACOBIANBOUNDARYCONSTXEND
%    JACOBIANFLIGHT = JACOBIANBOUNDARYCONSTXEND(XEND,ZEND,XDEND,ZDEND,G,K,BETA)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    02-Sep-2018 15:53:55

jacobianFlight = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[7,6]);
