function jacobianStance = jacobianPeriodicX0(l,theta,ld,thetad,g,k,beta)
%JACOBIANPERIODICX0
%    JACOBIANSTANCE = JACOBIANPERIODICX0(L,THETA,LD,THETAD,G,K,BETA)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    02-Sep-2018 15:32:50

t2 = conj(theta);
t3 = sin(t2);
t4 = cos(t2);
t5 = conj(l);
t6 = conj(thetad);
t7 = conj(ld);
t8 = t3.*t7;
t9 = t4.*t5.*t6;
t10 = t8+t9;
t11 = t3.*t5.*t6;
t12 = t11-t4.*t7;
jacobianStance = reshape([t4,-t3,-t3.*t6,-t4.*t6,1.0,0.0,t3.^2.*t5.*2.0+t4.*t6.*t10.*2.0,-t3.*t5,-t4.*t5,-t3.*t7-t4.*t5.*t6,t12,0.0,1.0,t10.*t12.*-2.0+t3.*t4.*t5.^2.*2.0,0.0,0.0,t4,-t3,0.0,0.0,t3.*t10.*2.0,0.0,0.0,-t3.*t5,-t4.*t5,0.0,0.0,t4.*t5.*t10.*2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[7,6]);
