function jacobianFlight = jacobianFlightDym(xb,zb,xbd,zbd,g)
%JACOBIANFLIGHTDYM
%    JACOBIANFLIGHT = JACOBIANFLIGHTDYM(XB,ZB,XBD,ZBD,G)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    30-Aug-2018 19:33:15

jacobianFlight = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0],[2,6]);
