function jacobianStanceEndPattern = jacobianBoundaryConstXSEndPattern
%JACOBIANBOUNDARYCONSTXSENDPATTERN
%    JACOBIANSTANCEENDPATTERN = JACOBIANBOUNDARYCONSTXSENDPATTERN

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    03-Sep-2018 14:32:28

jacobianStanceEndPattern = reshape([0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[9,6]);
