function jacobianStance0Pattern = jacobianBoundaryConstXS0Pattern
%JACOBIANBOUNDARYCONSTXS0PATTERN
%    JACOBIANSTANCE0PATTERN = JACOBIANBOUNDARYCONSTXS0PATTERN

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    03-Sep-2018 14:32:28

jacobianStance0Pattern = reshape([1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[9,6]);
