function jacobianFlight0Pattern = jacobianBoundaryConstXF0Pattern
%JACOBIANBOUNDARYCONSTXF0PATTERN
%    JACOBIANFLIGHT0PATTERN = JACOBIANBOUNDARYCONSTXF0PATTERN

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    04-Sep-2018 13:36:12

jacobianFlight0Pattern = reshape([0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[13,6]);
