function jacobianFlight = jacobianPeriodicXEnd(xEnd,zEnd,xdEnd,zdEnd,g,k,beta)
%JACOBIANPERIODICXEND
%    JACOBIANFLIGHT = JACOBIANPERIODICXEND(XEND,ZEND,XDEND,ZDEND,G,K,BETA)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    02-Sep-2018 15:32:50

jacobianFlight = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[7,6]);
