function jacobianCostStanceX = jacobianCostStanceX(l,theta,ld,thetad,h,g)
%JACOBIANCOSTSTANCEX
%    JACOBIANCOSTSTANCEX = JACOBIANCOSTSTANCEX(L,THETA,LD,THETAD,H,G)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    11-Sep-2018 00:57:11

jacobianCostStanceX = [h.*(l.*thetad.^2.*2.0-g.*sin(theta)),-g.*h.*l.*cos(theta),h.*ld.*2.0,h.*l.^2.*thetad.*2.0,0.0,0.0];
