function jacobianFlight0 = jacobianBoundaryConstXF0(xF0,zF0,xF0d,zF0d,g,k,beta)
%JACOBIANBOUNDARYCONSTXF0
%    JACOBIANFLIGHT0 = JACOBIANBOUNDARYCONSTXF0(XF0,ZF0,XF0D,ZF0D,G,K,BETA)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    04-Sep-2018 13:36:12

jacobianFlight0 = reshape([0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[13,6]);
