function jacobianStanceEndPattern = jacobianBoundaryCostXEndPattern
%JACOBIANBOUNDARYCOSTXENDPATTERN
%    JACOBIANSTANCEENDPATTERN = JACOBIANBOUNDARYCOSTXENDPATTERN

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    10-Sep-2018 16:12:29

jacobianStanceEndPattern = reshape([1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0],[2,6]);
