function jacobianFlight = jacobianFlightDym(xb,zb,xbd,zbd,g,k)
%JACOBIANFLIGHTDYM
%    JACOBIANFLIGHT = JACOBIANFLIGHTDYM(XB,ZB,XBD,ZBD,G,K)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    02-Sep-2018 11:26:57

jacobianFlight = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0],[2,6]);
