function jacobianStance0Pattern = jacobianBoundaryConstXS0SinglePattern
%JACOBIANBOUNDARYCONSTXS0SINGLEPATTERN
%    JACOBIANSTANCE0PATTERN = JACOBIANBOUNDARYCONSTXS0SINGLEPATTERN

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    07-Sep-2018 00:05:34

jacobianStance0Pattern = reshape([1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,6]);
