function jacobianFlightEnd = jacobianBoundaryConstXFEnd(xFEnd,zFEnd,xFEndd,zFEndd,g,k,beta)
%JACOBIANBOUNDARYCONSTXFEND
%    JACOBIANFLIGHTEND = JACOBIANBOUNDARYCONSTXFEND(XFEND,ZFEND,XFENDD,ZFENDD,G,K,BETA)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    04-Sep-2018 13:36:13

jacobianFlightEnd = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[13,6]);
