function jacobianStanceEndPattern = jacobianBoundaryConstXSEndSinglePattern
%JACOBIANBOUNDARYCONSTXSENDSINGLEPATTERN
%    JACOBIANSTANCEENDPATTERN = JACOBIANBOUNDARYCONSTXSENDSINGLEPATTERN

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    08-Sep-2018 11:26:36

jacobianStanceEndPattern = reshape([1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[4,6]);
