function jacobianFlightEndPattern = jacobianBoundaryConstXFEndPattern
%JACOBIANBOUNDARYCONSTXFENDPATTERN
%    JACOBIANFLIGHTENDPATTERN = JACOBIANBOUNDARYCONSTXFENDPATTERN

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    03-Sep-2018 14:32:30

jacobianFlightEndPattern = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[9,6]);
