function jacobianStanceEnd = jacobianBoundaryConstXSEndSingleFake(lEnd,thetaEnd,lEndd,thetaEndd,g,k,beta)
%JACOBIANBOUNDARYCONSTXSENDSINGLEFAKE
%    JACOBIANSTANCEEND = JACOBIANBOUNDARYCONSTXSENDSINGLEFAKE(LEND,THETAEND,LENDD,THETAENDD,G,K,BETA)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    06-Sep-2018 18:03:20

t2 = sin(thetaEnd);
t3 = cos(thetaEnd);
jacobianStanceEnd = reshape([0.0,t2.*thetaEndd.*1.0e1,t3.*thetaEndd.*1.0e1,0.0,lEndd.*t2.*1.0e1+lEnd.*t3.*thetaEndd.*1.0e1,lEndd.*t3.*1.0e1-lEnd.*t2.*thetaEndd.*1.0e1,0.0,t3.*-1.0e1,t2.*1.0e1,0.0,lEnd.*t2.*1.0e1,lEnd.*t3.*1.0e1,0.0,0.0,0.0,0.0,0.0,0.0],[3,6]);
