function jacobianStance0Pattern = jacobianBoundaryConstXS0SinglePatternFake
%JACOBIANBOUNDARYCONSTXS0SINGLEPATTERNFAKE
%    JACOBIANSTANCE0PATTERN = JACOBIANBOUNDARYCONSTXS0SINGLEPATTERNFAKE

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    08-Sep-2018 11:26:37

jacobianStance0Pattern = reshape([0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[4,6]);
