function jacobianStance0 = jacobianBoundaryConstXS0(l0,theta0,l0d,theta0d,g,k,beta)
%JACOBIANBOUNDARYCONSTXS0
%    JACOBIANSTANCE0 = JACOBIANBOUNDARYCONSTXS0(L0,THETA0,L0D,THETA0D,G,K,BETA)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    04-Sep-2018 13:36:12

t2 = sin(theta0);
t3 = cos(theta0);
jacobianStance0 = reshape([t3,-t2,-t2.*theta0d,-t3.*theta0d,0.0,0.0,0.0,0.0,1.0,0.0,0.0,l0.*theta0d.^2.*2.0,0.0,-l0.*t2,-l0.*t3,-l0d.*t2-l0.*t3.*theta0d,-l0d.*t3+l0.*t2.*theta0d,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,t3,-t2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,l0d.*2.0,0.0,0.0,0.0,-l0.*t2,-l0.*t3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,l0.^2.*theta0d.*2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[13,6]);
