function jacobianStanceEndPattern = jacobianBoundaryConstXSEndSinglePatternFake
%JACOBIANBOUNDARYCONSTXSENDSINGLEPATTERNFAKE
%    JACOBIANSTANCEENDPATTERN = JACOBIANBOUNDARYCONSTXSENDSINGLEPATTERNFAKE

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    07-Sep-2018 00:05:35

jacobianStanceEndPattern = reshape([0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,6]);
