function jacobianFlightEndPattern = jacobianBoundaryConstXFEndPattern
%JACOBIANBOUNDARYCONSTXFENDPATTERN
%    JACOBIANFLIGHTENDPATTERN = JACOBIANBOUNDARYCONSTXFENDPATTERN

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    04-Sep-2018 13:36:13

jacobianFlightEndPattern = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[13,6]);
