function jacobianStance0Pattern = jacobianBoundaryConstX0Pattern
%JACOBIANBOUNDARYCONSTX0PATTERN
%    JACOBIANSTANCE0PATTERN = JACOBIANBOUNDARYCONSTX0PATTERN

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    09-Sep-2018 10:00:21

jacobianStance0Pattern = [1.0,1.0,1.0,1.0,0.0,0.0];
