function jacobianCostStanceX = jacobianCostStanceX(l,theta,ld,thetad,h,g)
%JACOBIANCOSTSTANCEX
%    JACOBIANCOSTSTANCEX = JACOBIANCOSTSTANCEX(L,THETA,LD,THETAD,H,G)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    10-Sep-2018 22:35:00

t2 = sin(ld);
t3 = cos(ld);
t4 = t2.*theta;
t5 = l.*t3.*thetad;
t6 = t4+t5;
jacobianCostStanceX = [h.*(l.*t2.^2.*2.0-g.*t2.*thetad+t3.*t6.*thetad.*2.0),h.*(g.*t3+t2.*t6.*2.0),h.*(t6.*(t3.*theta-l.*t2.*thetad).*2.0-g.*t6+l.^2.*t2.*t3.*2.0),-h.*(g.*l.*t2-l.*t3.*t6.*2.0),0.0,0.0];
