function jacobianCostFlightX = jacobianCostFlightX(xF,zF,xFd,zFd,h)
%JACOBIANCOSTFLIGHTX
%    JACOBIANCOSTFLIGHTX = JACOBIANCOSTFLIGHTX(XF,ZF,XFD,ZFD,H)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    03-Sep-2018 19:41:32

jacobianCostFlightX = [0.0,0.0,h.*xFd.*2.0,h.*zFd.*2.0,0.0,0.0];
