function pointMassMotionVector = motionCOM2PointMass(xc,zc,phi,dxc,dzc,dphi,rc,mf)
%MOTIONCOM2POINTMASS
%    POINTMASSMOTIONVECTOR = MOTIONCOM2POINTMASS(XC,ZC,PHI,DXC,DZC,DPHI,RC,MF)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    13-Aug-2018 18:43:31

t2 = mf+1.0;
t3 = 1.0./t2;
t4 = sin(phi);
t5 = cos(phi);
pointMassMotionVector = [xc+rc.*t3.*t4;zc+rc.*t3.*t5;xc-mf.*rc.*t3.*t4;zc-mf.*rc.*t3.*t5;dxc+dphi.*rc.*t3.*t5;dzc-dphi.*rc.*t3.*t4;dxc-dphi.*mf.*rc.*t3.*t5;dzc+dphi.*mf.*rc.*t3.*t4];
