function c = boundaryConst(l0,theta0,l0d,theta0d,lEnd,thetaEnd,lEndd,thetaEndd,xF0,zF0,xF0d,zF0d,xFEnd,zFEnd,xFEndd,zFEndd,g,k,beta)
%BOUNDARYCONST
%    C = BOUNDARYCONST(L0,THETA0,L0D,THETA0D,LEND,THETAEND,LENDD,THETAENDD,XF0,ZF0,XF0D,ZF0D,XFEND,ZFEND,XFENDD,ZFENDD,G,K,BETA)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    05-Sep-2018 10:28:19

t2 = cos(theta0);
t3 = sin(theta0);
t4 = cos(thetaEnd);
t5 = sin(thetaEnd);
c = [xFEnd+l0.*t2,zFEnd-l0.*t3,xFEndd+l0d.*t2-l0.*t3.*theta0d,zFEndd-l0d.*t3-l0.*t2.*theta0d,xF0+lEnd.*t4,zF0+lEndd.*t4-lEnd.*t5.*thetaEndd,xF0d-lEnd.*t5,zF0d-lEndd.*t5-lEnd.*t4.*thetaEndd,l0-1.0,-beta+theta0,lEnd-1.0,l0d.^2+l0.^2.*theta0d.^2-1.0,xFEnd-3.0./1.0e1];
