function costFlight = costFlight(xF,zF,xFd,zFd,h,g)
%COSTFLIGHT
%    COSTFLIGHT = COSTFLIGHT(XF,ZF,XFD,ZFD,H,G)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    04-Sep-2018 13:56:14

costFlight = h.*(g.*zF+xFd.^2+zFd.^2);
