function jacobianStanceEndPattern = jacobianBoundaryConstXSEndPattern
%JACOBIANBOUNDARYCONSTXSENDPATTERN
%    JACOBIANSTANCEENDPATTERN = JACOBIANBOUNDARYCONSTXSENDPATTERN

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    05-Sep-2018 10:28:20

jacobianStanceEndPattern = reshape([0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[13,6]);
