function jacobianStanceEndPattern = jacobianBoundaryCostXEndPattern
%JACOBIANBOUNDARYCOSTXENDPATTERN
%    JACOBIANSTANCEENDPATTERN = JACOBIANBOUNDARYCOSTXENDPATTERN

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    11-Sep-2018 11:17:32

jacobianStanceEndPattern = reshape([1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0],[2,6]);
