function jacobianStance0Pattern = jacobianBoundaryConstXS0Pattern
%JACOBIANBOUNDARYCONSTXS0PATTERN
%    JACOBIANSTANCE0PATTERN = JACOBIANBOUNDARYCONSTXS0PATTERN

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    05-Sep-2018 10:28:20

jacobianStance0Pattern = reshape([1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[13,6]);
