function jacobianCostStanceX = jacobianCostStanceX(l,theta,ld,thetad,h,g,k)
%JACOBIANCOSTSTANCEX
%    JACOBIANCOSTSTANCEX = JACOBIANCOSTSTANCEX(L,THETA,LD,THETAD,H,G,K)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    11-Sep-2018 11:40:03

jacobianCostStanceX = [h.*(k-k.*l+l.*thetad.^2-g.*sin(theta)),-g.*h.*l.*cos(theta),h.*ld,h.*l.^2.*thetad,0.0,0.0];
