function jacobianFlightEndPattern = jacobianBoundaryConstXFEndPattern
%JACOBIANBOUNDARYCONSTXFENDPATTERN
%    JACOBIANFLIGHTENDPATTERN = JACOBIANBOUNDARYCONSTXFENDPATTERN

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    05-Sep-2018 10:28:20

jacobianFlightEndPattern = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[13,6]);
