function jacobianCostFlightH = jacobianCostFlightH(xF,zF,xFd,zFd,h,g)
%JACOBIANCOSTFLIGHTH
%    JACOBIANCOSTFLIGHTH = JACOBIANCOSTFLIGHTH(XF,ZF,XFD,ZFD,H,G)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    11-Sep-2018 00:57:11

jacobianCostFlightH = g.*zF+xFd.^2+zFd.^2;
