function jacobianStance0Pattern = jacobianBoundaryCostX0Pattern
%JACOBIANBOUNDARYCOSTX0PATTERN
%    JACOBIANSTANCE0PATTERN = JACOBIANBOUNDARYCOSTX0PATTERN

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    11-Sep-2018 11:17:31

jacobianStance0Pattern = reshape([1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0],[2,6]);
