function posStance = myfile(t)
%MYFILE
%    POSSTANCE = MYFILE(T)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    11-Aug-2018 12:57:23

t2 = theta(t);
t3 = l(t);
posStance = [-t3.*cos(t2);t3.*sin(t2)];
