function pointMassMotionVector = motionCOM2PointMass(xc,zc,phi,xcd,zcd,phid,rc,mf)
%MOTIONCOM2POINTMASS
%    POINTMASSMOTIONVECTOR = MOTIONCOM2POINTMASS(XC,ZC,PHI,XCD,ZCD,PHID,RC,MF)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    13-Aug-2018 22:34:43

t2 = mf+1.0;
t3 = 1.0./t2;
t4 = sin(phi);
t5 = cos(phi);
pointMassMotionVector = [xc+rc.*t3.*t4;zc+rc.*t3.*t5;xc-mf.*rc.*t3.*t4;zc-mf.*rc.*t3.*t5;xcd+phid.*rc.*t3.*t5;zcd-phid.*rc.*t3.*t4;xcd-mf.*phid.*rc.*t3.*t5;zcd+mf.*phid.*rc.*t3.*t4];
