function comMotion = motionPointMass2COM(xf,zf,xb,zb,xfd,zfd,xbd,zbd,rc,mf)
%MOTIONPOINTMASS2COM
%    COMMOTION = MOTIONPOINTMASS2COM(XF,ZF,XB,ZB,XFD,ZFD,XBD,ZBD,RC,MF)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    13-Aug-2018 22:34:43

t2 = mf+1.0;
t3 = 1.0./t2;
comMotion = [t3.*xb+mf.*t3.*xf;t3.*zb+mf.*t3.*zf;t3.*xbd+mf.*t3.*xfd;t3.*zbd+mf.*t3.*zfd];
